SIFT_LOCATION = 'sift_100.pkl'
RSIFT_LOCATION = 'rsift_100.pkl'
FEATURE_LIST_LOCATION = 'feature_list_100.pkl'
KMEANS_LOCATION = 'kmeans.pkl'
CENTROIDS_FILES_LOCATION = 'centroids_files.pkl'
CENTROIDS_LOCATION = 'centroids.pkl'
